spring:
  datasource:
   url: jdbc:mysql://192.168.222.129:3306/mybatis?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
   username: root
   password: 123456
   #hikari:
   # maximum-pool-size: 20
   driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.mybatis.model
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8204
